package tanin.backdoor;

public class TreeNames {
  public static final String[] TREE_NAMES = {
    "acacia",
    "alder",
    "ash",
    "aspen",
    "baobab",
    "beech",
    "birch",
    "cedar",
    "cherry",
    "chestnut",
    "cypress",
    "dogwood",
    "elm",
    "eucalyptus",
    "fir",
    "ginkgo",
    "hemlock",
    "hickory",
    "juniper",
    "larch",
    "linden",
    "locust",
    "magnolia",
    "maple",
    "mulberry",
    "oak",
    "palm",
    "pecan",
    "pine",
    "poplar",
    "redwood",
    "sequoia",
    "spruce",
    "sycamore",
    "walnut",
    "willow",
  };
}
